### ISSUE TITLE
NEW idea

### ISSUE THREAD

**Issue by shiuanyue** [battlemage64/PeopleCanChange#1]
I hope that Trait names can automatically reference the Core language package.

It looks like
Trait: Optimist→Trait: {Optimist.label}

The names can change with Core version updates.

**Comment by battlemage64** [comment]
Good idea! I just added this. Now instead of saying:
AnnoyingVoice
It will say:
English: AnnoyingVoice (annoying voice)
German: AnnoyingVoice (nervige Stimme)
Chinese (Traditional): AnnoyingVoice (喋喋不休)
and so on, for any trait and language
